apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 3  # Specify the desired number of pod replicas
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow-container
        image: <your-docker-image>:<tag>  # Replace with your Docker image name and tag
        ports:
        - containerPort: 4499  # Specify the port on which the Wisecow application listens
