apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 4499  # Specify the port on which the service will listen
      targetPort: 4499  # Specify the port on which the pods are listening
  type: ClusterIP  # Use ClusterIP for internal service within the cluster
